export const UPDATE_COLOR: string = 'UPDATE_COLOR';
export enum ActionType {
    UPDATE_COLOR = 'UPDATE_COLOR',
    SETTINGS_COLORS_RESTORE_INIT = 'SETTINGS_COLORS_RESTORE_INIT',
    SETTINGS_COLORS_RESTORE_PENDING = 'SETTINGS_COLORS_RESTORE_PENDING',
    SETTINGS_COLORS_RESTORE_SUCCESS = 'SETTINGS_COLORS_RESTORE_SUCCESS',
    SETTINGS_COLORS_RESTORE_FAIL = 'SETTINGS_COLORS_RESTORE_FAIL',
}
